import type {
  Program,
  Researcher,
  Report,
  DashboardStats,
  OrgDashboardStats,
  PlatformStats,
  ChartDataPoint,
  TimelineDataPoint,
} from './types'

export const platformStats: PlatformStats = {
  activePrograms: 24,
  verifiedResearchers: 312,
  reportsSubmitted: 1847,
  avgTriageTime: '< 24h',
  rewardsPaid: 127500,
  organizationsJoined: 18,
}

export const programs: Program[] = [
  {
    id: '1',
    name: 'CaspianBank Security Program',
    organization: 'CaspianBank',
    slug: 'caspianbank',
    description: 'Help secure Azerbaijan\'s leading digital banking platform. Test our web and mobile applications for vulnerabilities.',
    longDescription: 'CaspianBank is committed to maintaining the highest security standards for our digital banking services. We invite security researchers to help us identify vulnerabilities in our systems. Our program covers web applications, mobile apps, and public APIs. We value detailed reports and reward researchers generously for valid findings.',
    industry: 'Financial Services',
    status: 'active',
    type: 'bug-bounty',
    rewardRange: { min: 100, max: 5000 },
    assetsCount: 8,
    lastUpdated: '2026-04-20',
    tags: ['Web', 'API', 'Mobile', 'Finance'],
    featured: true,
    inScope: [
      { target: 'app.caspianbank.demo', type: 'web', description: 'Main web application' },
      { target: 'api.caspianbank.demo', type: 'api', description: 'Public REST API' },
      { target: 'mobile.caspianbank.demo', type: 'mobile', description: 'Android & iOS apps' },
      { target: 'portal.caspianbank.demo', type: 'web', description: 'Customer login portal' },
    ],
    outOfScope: [
      'Social engineering attacks',
      'DDoS or denial of service',
      'Physical security testing',
      'Attacks against third-party services',
      'Spam or rate-limit bypass without security impact',
      'Self-XSS without impact',
    ],
    rewards: [
      { severity: 'critical', minReward: 2500, maxReward: 5000, sla: '24 hours' },
      { severity: 'high', minReward: 1000, maxReward: 2500, sla: '48 hours' },
      { severity: 'medium', minReward: 300, maxReward: 1000, sla: '72 hours' },
      { severity: 'low', minReward: 100, maxReward: 300, sla: '5 days' },
    ],
    rules: [
      'Do not access, modify, or delete user data',
      'Do not perform destructive testing',
      'Report vulnerabilities promptly',
      'Do not disclose findings publicly until resolved',
      'Test only on designated test accounts',
      'Follow responsible disclosure practices',
    ],
    updates: [
      { id: '1', date: '2026-04-20', title: 'Mobile app v3.0 added to scope', description: 'Our new mobile banking app is now in scope for testing.', type: 'scope' },
      { id: '2', date: '2026-04-10', title: 'Increased critical rewards', description: 'Critical vulnerabilities now pay up to $5,000.', type: 'reward' },
      { id: '3', date: '2026-03-25', title: 'API v2 endpoints added', description: 'New API version 2 endpoints are now in scope.', type: 'scope' },
      { id: '4', date: '2026-03-15', title: 'Safe Harbor policy updated', description: 'Enhanced legal protections for researchers.', type: 'policy' },
    ],
    hallOfFame: [
      { researcherId: '1', name: 'CyberNomad', points: 4500, reportsAccepted: 12, rank: 1 },
      { researcherId: '2', name: 'BugSlayer_AZ', points: 3200, reportsAccepted: 8, rank: 2 },
      { researcherId: '3', name: 'SecurityPro', points: 2100, reportsAccepted: 6, rank: 3 },
    ],
    responseTime: {
      firstResponse: '< 4 hours',
      triage: '< 24 hours',
      resolution: '< 30 days',
    },
  },
  {
    id: '2',
    name: 'BakuCommerce Platform',
    organization: 'BakuCommerce',
    slug: 'bakucommerce',
    description: 'Secure e-commerce for the Caspian region. Test our marketplace and payment systems.',
    longDescription: 'BakuCommerce operates the largest e-commerce marketplace in Azerbaijan. Security is critical to our platform as we handle sensitive payment and customer data. We welcome researchers to test our web platform, merchant APIs, and mobile applications.',
    industry: 'E-Commerce',
    status: 'active',
    type: 'bug-bounty',
    rewardRange: { min: 50, max: 3000 },
    assetsCount: 6,
    lastUpdated: '2026-04-18',
    tags: ['Web', 'API', 'Payments'],
    featured: true,
    inScope: [
      { target: 'www.bakucommerce.demo', type: 'web', description: 'Main marketplace' },
      { target: 'seller.bakucommerce.demo', type: 'web', description: 'Merchant portal' },
      { target: 'api.bakucommerce.demo', type: 'api', description: 'Merchant API' },
    ],
    outOfScope: [
      'Third-party seller content',
      'Social engineering',
      'Physical attacks',
      'Rate limiting without security impact',
    ],
    rewards: [
      { severity: 'critical', minReward: 1500, maxReward: 3000, sla: '24 hours' },
      { severity: 'high', minReward: 500, maxReward: 1500, sla: '48 hours' },
      { severity: 'medium', minReward: 150, maxReward: 500, sla: '72 hours' },
      { severity: 'low', minReward: 50, maxReward: 150, sla: '5 days' },
    ],
    rules: [
      'Do not access real customer data',
      'Use test accounts only',
      'No automated scanning without approval',
      'Report findings confidentially',
    ],
    updates: [
      { id: '1', date: '2026-04-18', title: 'Payment gateway in scope', description: 'New payment processing system added to scope.', type: 'scope' },
    ],
    hallOfFame: [
      { researcherId: '2', name: 'BugSlayer_AZ', points: 2800, reportsAccepted: 7, rank: 1 },
      { researcherId: '4', name: 'HackerBaku', points: 1900, reportsAccepted: 5, rank: 2 },
    ],
    responseTime: {
      firstResponse: '< 8 hours',
      triage: '< 48 hours',
      resolution: '< 45 days',
    },
  },
  {
    id: '3',
    name: 'GovPortal X',
    organization: 'Digital Government Initiative',
    slug: 'govportal-x',
    description: 'Vulnerability disclosure program for government digital services portal.',
    longDescription: 'GovPortal X is the unified government services platform serving millions of citizens. As a vulnerability disclosure program, we focus on identifying security issues to protect citizen data. This program emphasizes responsible disclosure over monetary rewards.',
    industry: 'Government',
    status: 'active',
    type: 'vdp',
    rewardRange: { min: 0, max: 500 },
    assetsCount: 12,
    lastUpdated: '2026-04-15',
    tags: ['Web', 'Government', 'Public Services'],
    featured: true,
    inScope: [
      { target: 'portal.govx.demo', type: 'web', description: 'Citizen services portal' },
      { target: 'auth.govx.demo', type: 'web', description: 'Authentication system' },
      { target: 'docs.govx.demo', type: 'web', description: 'Document management' },
    ],
    outOfScope: [
      'Classified systems',
      'Internal admin panels',
      'Physical infrastructure',
      'Social engineering of staff',
    ],
    rewards: [
      { severity: 'critical', minReward: 250, maxReward: 500, sla: '24 hours' },
      { severity: 'high', minReward: 100, maxReward: 250, sla: '48 hours' },
      { severity: 'medium', minReward: 50, maxReward: 100, sla: '72 hours' },
      { severity: 'low', minReward: 0, maxReward: 50, sla: '7 days' },
    ],
    rules: [
      'Citizens\' data must not be accessed',
      'Report through official channels only',
      'No public disclosure',
      'Coordinate with security team',
    ],
    updates: [
      { id: '1', date: '2026-04-15', title: 'New authentication flow in scope', description: 'Updated single sign-on system now included.', type: 'scope' },
    ],
    hallOfFame: [
      { researcherId: '1', name: 'CyberNomad', points: 1200, reportsAccepted: 4, rank: 1 },
    ],
    responseTime: {
      firstResponse: '< 24 hours',
      triage: '< 72 hours',
      resolution: '< 60 days',
    },
  },
  {
    id: '4',
    name: 'AzCloud One',
    organization: 'AzCloud Technologies',
    slug: 'azcloud-one',
    description: 'Cloud infrastructure and hosting platform security program.',
    longDescription: 'AzCloud One provides enterprise cloud infrastructure for businesses across the region. Our bug bounty program covers our control panel, APIs, and customer-facing services. We are particularly interested in cloud security vulnerabilities.',
    industry: 'Cloud & Infrastructure',
    status: 'active',
    type: 'bug-bounty',
    rewardRange: { min: 200, max: 7500 },
    assetsCount: 15,
    lastUpdated: '2026-04-22',
    tags: ['Cloud', 'API', 'Infrastructure'],
    featured: true,
    inScope: [
      { target: 'console.azcloud.demo', type: 'web', description: 'Cloud management console' },
      { target: 'api.azcloud.demo', type: 'api', description: 'Cloud API' },
      { target: 'storage.azcloud.demo', type: 'cloud', description: 'Object storage service' },
      { target: 'compute.azcloud.demo', type: 'cloud', description: 'Compute instances' },
    ],
    outOfScope: [
      'Customer VMs and data',
      'Third-party integrations',
      'DDoS attacks',
      'Internal corporate systems',
    ],
    rewards: [
      { severity: 'critical', minReward: 5000, maxReward: 7500, sla: '12 hours' },
      { severity: 'high', minReward: 2000, maxReward: 5000, sla: '24 hours' },
      { severity: 'medium', minReward: 500, maxReward: 2000, sla: '48 hours' },
      { severity: 'low', minReward: 200, maxReward: 500, sla: '5 days' },
    ],
    rules: [
      'Do not access other customers\' infrastructure',
      'Test only on your own resources',
      'Report privilege escalation immediately',
      'No data exfiltration attempts',
    ],
    updates: [
      { id: '1', date: '2026-04-22', title: 'Kubernetes service added', description: 'Managed Kubernetes now in scope.', type: 'scope' },
      { id: '2', date: '2026-04-05', title: 'Premium rewards for cloud escapes', description: 'VM escape vulnerabilities now pay up to $7,500.', type: 'reward' },
    ],
    hallOfFame: [
      { researcherId: '3', name: 'SecurityPro', points: 5500, reportsAccepted: 9, rank: 1 },
      { researcherId: '1', name: 'CyberNomad', points: 3800, reportsAccepted: 6, rank: 2 },
    ],
    responseTime: {
      firstResponse: '< 2 hours',
      triage: '< 12 hours',
      resolution: '< 21 days',
    },
  },
  {
    id: '5',
    name: 'SilkRoute Pay',
    organization: 'SilkRoute Financial',
    slug: 'silkroute-pay',
    description: 'Digital payments and fintech security testing program.',
    longDescription: 'SilkRoute Pay is a next-generation payment platform connecting merchants and consumers. We handle sensitive financial data and transactions, making security our top priority. Researchers are rewarded generously for payment-related vulnerabilities.',
    industry: 'Fintech',
    status: 'active',
    type: 'bug-bounty',
    rewardRange: { min: 150, max: 6000 },
    assetsCount: 7,
    lastUpdated: '2026-04-19',
    tags: ['Payments', 'API', 'Mobile', 'Fintech'],
    featured: false,
    inScope: [
      { target: 'pay.silkroute.demo', type: 'web', description: 'Payment portal' },
      { target: 'merchant.silkroute.demo', type: 'web', description: 'Merchant dashboard' },
      { target: 'api.silkroute.demo', type: 'api', description: 'Payment API' },
      { target: 'app.silkroute.demo', type: 'mobile', description: 'Mobile wallet app' },
    ],
    outOfScope: [
      'Real financial transactions',
      'Third-party payment processors',
      'Partner bank systems',
      'Physical card attacks',
    ],
    rewards: [
      { severity: 'critical', minReward: 3500, maxReward: 6000, sla: '8 hours' },
      { severity: 'high', minReward: 1500, maxReward: 3500, sla: '24 hours' },
      { severity: 'medium', minReward: 400, maxReward: 1500, sla: '48 hours' },
      { severity: 'low', minReward: 150, maxReward: 400, sla: '5 days' },
    ],
    rules: [
      'Use test cards only',
      'No real money transactions',
      'Report PCI-related issues immediately',
      'Coordinate disclosure with compliance team',
    ],
    updates: [
      { id: '1', date: '2026-04-19', title: 'QR payment testing enabled', description: 'QR code payment flows now in scope.', type: 'scope' },
    ],
    hallOfFame: [
      { researcherId: '5', name: 'PayloadMaster', points: 4200, reportsAccepted: 8, rank: 1 },
    ],
    responseTime: {
      firstResponse: '< 4 hours',
      triage: '< 16 hours',
      resolution: '< 14 days',
    },
  },
  {
    id: '6',
    name: 'Karabug Telecom',
    organization: 'Karabug Communications',
    slug: 'karabug-telecom',
    description: 'Telecommunications and mobile network security program.',
    longDescription: 'Karabug Telecom is a major telecommunications provider. Our security program covers customer portals, mobile apps, and select network-adjacent systems. We are committed to protecting our customers\' communications.',
    industry: 'Telecommunications',
    status: 'upcoming',
    type: 'private-preview',
    rewardRange: { min: 100, max: 4000 },
    assetsCount: 5,
    lastUpdated: '2026-04-25',
    tags: ['Telecom', 'Mobile', 'API'],
    featured: false,
    inScope: [
      { target: 'my.karabug.demo', type: 'web', description: 'Customer portal' },
      { target: 'app.karabug.demo', type: 'mobile', description: 'Mobile app' },
    ],
    outOfScope: [
      'Network infrastructure',
      'Radio/cellular systems',
      'Partner systems',
      'Call interception attempts',
    ],
    rewards: [
      { severity: 'critical', minReward: 2500, maxReward: 4000, sla: '24 hours' },
      { severity: 'high', minReward: 1000, maxReward: 2500, sla: '48 hours' },
      { severity: 'medium', minReward: 300, maxReward: 1000, sla: '72 hours' },
      { severity: 'low', minReward: 100, maxReward: 300, sla: '7 days' },
    ],
    rules: [
      'Customer data is strictly off-limits',
      'No network scanning',
      'Test accounts provided upon request',
      'Weekly reporting cycles',
    ],
    updates: [
      { id: '1', date: '2026-04-25', title: 'Private preview launching soon', description: 'Accepting applications for early access.', type: 'general' },
    ],
    hallOfFame: [],
    responseTime: {
      firstResponse: '< 12 hours',
      triage: '< 48 hours',
      resolution: '< 45 days',
    },
  },
]

export const researchers: Researcher[] = [
  {
    id: '1',
    name: 'CyberNomad',
    handle: 'cybernomad',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    points: 12500,
    reportsAccepted: 42,
    reportsSubmitted: 58,
    reputation: 98,
    rank: 1,
    badges: [
      { id: '1', name: 'First Blood', description: 'First accepted report on a program', icon: 'target', earnedDate: '2025-06-15' },
      { id: '2', name: 'Critical Hunter', description: 'Found 5+ critical vulnerabilities', icon: 'shield', earnedDate: '2025-09-20' },
      { id: '3', name: 'Top 10', description: 'Ranked in top 10 researchers', icon: 'trophy', earnedDate: '2025-12-01' },
    ],
    joinedDate: '2025-03-10',
    totalRewards: 28500,
  },
  {
    id: '2',
    name: 'BugSlayer_AZ',
    handle: 'bugslayer_az',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    points: 9800,
    reportsAccepted: 35,
    reportsSubmitted: 48,
    reputation: 95,
    rank: 2,
    badges: [
      { id: '1', name: 'First Blood', description: 'First accepted report on a program', icon: 'target', earnedDate: '2025-05-20' },
      { id: '2', name: 'Speed Demon', description: 'Fastest triage to resolution', icon: 'zap', earnedDate: '2025-08-15' },
    ],
    joinedDate: '2025-04-05',
    totalRewards: 22300,
  },
  {
    id: '3',
    name: 'SecurityPro',
    handle: 'securitypro',
    country: 'Turkey',
    countryCode: 'TR',
    points: 8500,
    reportsAccepted: 28,
    reportsSubmitted: 35,
    reputation: 94,
    rank: 3,
    badges: [
      { id: '1', name: 'Cloud Expert', description: 'Specialized in cloud vulnerabilities', icon: 'cloud', earnedDate: '2025-10-10' },
    ],
    joinedDate: '2025-05-12',
    totalRewards: 19800,
  },
  {
    id: '4',
    name: 'HackerBaku',
    handle: 'hackerbaku',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    points: 7200,
    reportsAccepted: 24,
    reportsSubmitted: 32,
    reputation: 92,
    rank: 4,
    badges: [
      { id: '1', name: 'Web Wizard', description: 'Expert in web vulnerabilities', icon: 'globe', earnedDate: '2025-07-22' },
    ],
    joinedDate: '2025-06-18',
    totalRewards: 15600,
  },
  {
    id: '5',
    name: 'PayloadMaster',
    handle: 'payloadmaster',
    country: 'Georgia',
    countryCode: 'GE',
    points: 6800,
    reportsAccepted: 22,
    reportsSubmitted: 28,
    reputation: 91,
    rank: 5,
    badges: [
      { id: '1', name: 'API Hunter', description: 'Found 10+ API vulnerabilities', icon: 'code', earnedDate: '2025-11-05' },
    ],
    joinedDate: '2025-07-03',
    totalRewards: 14200,
  },
  {
    id: '6',
    name: 'NullByte',
    handle: 'nullbyte',
    country: 'Russia',
    countryCode: 'RU',
    points: 5900,
    reportsAccepted: 19,
    reportsSubmitted: 25,
    reputation: 89,
    rank: 6,
    badges: [],
    joinedDate: '2025-08-15',
    totalRewards: 11800,
  },
  {
    id: '7',
    name: 'VulnSeeker',
    handle: 'vulnseeker',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    points: 5200,
    reportsAccepted: 17,
    reportsSubmitted: 22,
    reputation: 88,
    rank: 7,
    badges: [],
    joinedDate: '2025-09-01',
    totalRewards: 9500,
  },
  {
    id: '8',
    name: 'XSSMaster',
    handle: 'xssmaster',
    country: 'Iran',
    countryCode: 'IR',
    points: 4800,
    reportsAccepted: 16,
    reportsSubmitted: 21,
    reputation: 87,
    rank: 8,
    badges: [],
    joinedDate: '2025-09-20',
    totalRewards: 8700,
  },
  {
    id: '9',
    name: 'CaspianHacker',
    handle: 'caspianhacker',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    points: 4200,
    reportsAccepted: 14,
    reportsSubmitted: 18,
    reputation: 85,
    rank: 9,
    badges: [],
    joinedDate: '2025-10-05',
    totalRewards: 7200,
  },
  {
    id: '10',
    name: 'BountyKing',
    handle: 'bountyking',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    points: 3800,
    reportsAccepted: 12,
    reportsSubmitted: 16,
    reputation: 84,
    rank: 10,
    badges: [],
    joinedDate: '2025-10-20',
    totalRewards: 6500,
  },
]

export const reports: Report[] = [
  {
    id: '1',
    title: 'SQL Injection in Search API',
    programId: '1',
    programName: 'CaspianBank',
    severity: 'critical',
    status: 'rewarded',
    submittedDate: '2026-04-10',
    lastUpdated: '2026-04-15',
    reward: 4500,
    asset: 'api.caspianbank.demo',
    weaknessType: 'SQL Injection',
  },
  {
    id: '2',
    title: 'IDOR in Account Settings',
    programId: '1',
    programName: 'CaspianBank',
    severity: 'high',
    status: 'resolved',
    submittedDate: '2026-04-08',
    lastUpdated: '2026-04-12',
    reward: 1800,
    asset: 'app.caspianbank.demo',
    weaknessType: 'Insecure Direct Object Reference',
  },
  {
    id: '3',
    title: 'XSS in Product Reviews',
    programId: '2',
    programName: 'BakuCommerce',
    severity: 'medium',
    status: 'triaged',
    submittedDate: '2026-04-18',
    lastUpdated: '2026-04-20',
    asset: 'www.bakucommerce.demo',
    weaknessType: 'Cross-Site Scripting',
  },
  {
    id: '4',
    title: 'Authentication Bypass via Token Manipulation',
    programId: '4',
    programName: 'AzCloud One',
    severity: 'critical',
    status: 'pending',
    submittedDate: '2026-04-22',
    lastUpdated: '2026-04-22',
    asset: 'console.azcloud.demo',
    weaknessType: 'Authentication Bypass',
  },
  {
    id: '5',
    title: 'CSRF in Password Change',
    programId: '3',
    programName: 'GovPortal X',
    severity: 'medium',
    status: 'resolved',
    submittedDate: '2026-04-05',
    lastUpdated: '2026-04-10',
    reward: 75,
    asset: 'portal.govx.demo',
    weaknessType: 'Cross-Site Request Forgery',
  },
  {
    id: '6',
    title: 'Information Disclosure in Error Messages',
    programId: '5',
    programName: 'SilkRoute Pay',
    severity: 'low',
    status: 'rewarded',
    submittedDate: '2026-04-15',
    lastUpdated: '2026-04-18',
    reward: 200,
    asset: 'api.silkroute.demo',
    weaknessType: 'Information Exposure',
  },
  {
    id: '7',
    title: 'Rate Limiting Bypass on Login',
    programId: '1',
    programName: 'CaspianBank',
    severity: 'medium',
    status: 'draft',
    submittedDate: '2026-04-24',
    lastUpdated: '2026-04-24',
    asset: 'app.caspianbank.demo',
    weaknessType: 'Improper Rate Limiting',
  },
]

export const researcherDashboardStats: DashboardStats = {
  totalReports: 58,
  acceptedReports: 42,
  pendingTriage: 3,
  totalRewards: 28500,
  reputationScore: 98,
  rank: 1,
}

export const orgDashboardStats: OrgDashboardStats = {
  totalReports: 247,
  openReports: 18,
  avgTriageTime: '18h',
  criticalFindings: 12,
  rewardsPaid: 87500,
  resolvedThisMonth: 24,
}

export const severityDistribution: ChartDataPoint[] = [
  { name: 'Critical', value: 15, fill: 'var(--chart-5)' },
  { name: 'High', value: 42, fill: 'var(--chart-4)' },
  { name: 'Medium', value: 98, fill: 'var(--chart-1)' },
  { name: 'Low', value: 67, fill: 'var(--chart-2)' },
  { name: 'Info', value: 25, fill: 'var(--chart-3)' },
]

export const reportsTimeline: TimelineDataPoint[] = [
  { month: 'Nov', reports: 12, resolved: 10 },
  { month: 'Dec', reports: 18, resolved: 15 },
  { month: 'Jan', reports: 24, resolved: 20 },
  { month: 'Feb', reports: 32, resolved: 28 },
  { month: 'Mar', reports: 28, resolved: 25 },
  { month: 'Apr', reports: 22, resolved: 18 },
]

export const researcherReportsTimeline: TimelineDataPoint[] = [
  { month: 'Nov', reports: 4 },
  { month: 'Dec', reports: 6 },
  { month: 'Jan', reports: 8 },
  { month: 'Feb', reports: 12 },
  { month: 'Mar', reports: 10 },
  { month: 'Apr', reports: 8 },
]

export const topAttackedAssets = [
  { asset: 'api.caspianbank.demo', reports: 45, severity: 'high' as const },
  { asset: 'console.azcloud.demo', reports: 38, severity: 'critical' as const },
  { asset: 'www.bakucommerce.demo', reports: 32, severity: 'medium' as const },
  { asset: 'portal.govx.demo', reports: 28, severity: 'medium' as const },
  { asset: 'pay.silkroute.demo', reports: 24, severity: 'high' as const },
]

export const recentActivity = [
  { id: '1', action: 'Report triaged', target: 'SQL Injection in Search API', time: '2 hours ago', type: 'triage' },
  { id: '2', action: 'Reward paid', target: 'IDOR in Account Settings', time: '4 hours ago', type: 'reward' },
  { id: '3', action: 'New report received', target: 'Authentication Bypass', time: '6 hours ago', type: 'new' },
  { id: '4', action: 'Report resolved', target: 'XSS in Product Reviews', time: '8 hours ago', type: 'resolved' },
  { id: '5', action: 'Program updated', target: 'AzCloud One - New scope', time: '12 hours ago', type: 'update' },
]

export const weaknessCategories = [
  'SQL Injection',
  'Cross-Site Scripting (XSS)',
  'Cross-Site Request Forgery (CSRF)',
  'Insecure Direct Object Reference (IDOR)',
  'Authentication Bypass',
  'Authorization Bypass',
  'Information Disclosure',
  'Server-Side Request Forgery (SSRF)',
  'XML External Entity (XXE)',
  'Remote Code Execution (RCE)',
  'Open Redirect',
  'Improper Input Validation',
  'Cryptographic Issues',
  'Session Management',
  'Business Logic Flaw',
  'Other',
]

export const industries = [
  'Financial Services',
  'E-Commerce',
  'Government',
  'Cloud & Infrastructure',
  'Fintech',
  'Telecommunications',
  'Healthcare',
  'Education',
  'Media & Entertainment',
  'Other',
]
